apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: api
          image: johary94/todo-api:latest
          env:
            - name: DB_HOST
              value: "todo-db-service"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "postgres"
            - name: DB_NAME
              value: "tasksdb"
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 3000
